### ISSUE TITLE
enum in proto=3 give a duplicate enum registered

### ISSUE THREAD

**Issue by albertog** [peter-edge/protoeasy-go#2]
enum not work propertly give a duplicate enum registered when you use under appengine.

**Comment by peter-edge** [comment]
Hey,

Thanks for filing the issue - can you provide me an example to reproduce?

**Comment by albertog** [comment]
I have sent a email for privacy reason.

**Comment by peter-edge** [comment]
Talked privately, it looks like this is an appengine issue and not a protoeasy issue. Closing for now, but feel free to re-open if we are wrong.
