### ISSUE TITLE
try with dlite

### ISSUE THREAD

**Issue by joeblew99** [peter-edge/protoeasy-go#4]
this is a great project, and makes getting things going really easy.

To make it even easier, what about also supporting dlite (https://github.com/nlf/dlite) ?
Most people are getting it working with no problems now on OSX.
Of course the virtualBox method should also be provided.

**Comment by peter-edge** [comment]
Hey,

Thanks for the suggestion. Protoeasy should just work within dlite, right? Protoeasy does not care where the docket daemon is running.

**Comment by peter-edge** [comment]
You should just do:

export PROTOEASY_ADDRESS=local.docker:6789

**Comment by joeblew99** [comment]
That's all ? Too easy

**Comment by peter-edge** [comment]
Life can be hard and life can be easy, the variation makes it fun :)

**Comment by joeblew99** [comment]
Cheers :) closing..
