### ISSUE TITLE
question: javascript

### ISSUE THREAD

**Issue by joeblew99** [peter-edge/protoeasy-go#5]
The GRPC-REST gateway aspects are a huge time saver. thank you for this.
But i am needing to generate JavaScript proxies and wanted to raise this and ask for advice, and maybe i can contribute this.

As i understand it the https://github.com/gengo/grpc-gateway code can also prodcued a swagger.json file ?
That means that JS clients can also be produced ?
I know that means no true RPC, because web sockets are not part of swagger, but from what i have reas on open api code, they are looking into adding WebSockets.

Any advice. help, interest in this ?

**Comment by joeblew99** [comment]
Here are the go gets from the grpc-gateway page at https://github.com/gengo/grpc-gateway:

go get -u github.com/gengo/grpc-gateway/protoc-gen-grpc-gateway
go get -u github.com/gengo/grpc-gateway/protoc-gen-swagger
go get -u github.com/golang/protobuf/protoc-gen-go

So its seems they clearly are now enabling swagger and that opens up the world to generating client proxy code in JS, but all many of others.

**Comment by peter-edge** [comment]
See my comments on https://github.com/peter-edge/protoeasy-go/pull/10
