### ISSUE TITLE
Invalid certificate on go.pedge.io

### ISSUE THREAD

**Issue by charith-qubit** [peter-edge/protoeasy-go#8]
@peter-edge Not sure whether you are aware, so I thought I would raise it here just in case.  It looks like the certificate on go.pedge.io is now invalid. Running `go get go.pedge.io/protoeasy/cmd/protoeasy` returns `https fetch: Get https://go.pedge.io/protoeasy/cmd/protoeasy?go-get=1: x509: certificate signed by unknown authority`. 

Any plans to update it?

**Comment by peter-edge** [comment]
Hey,

My apologies, will try to get this fixed soon.

**Comment by graywolf336** [comment]
Any status update?

**Comment by peter-edge** [comment]
Sorry for the delay - I just spent a few hours redoing the deployment, this should be fixed now, reopen if not.
